repos:
  - repo: local
    hooks:
      - id: treefmt
        name: treefmt
        entry: treefmt
        language: system
        pass_filenames: false
        stages: [commit]
      - id: detect-secrets
        name: detect-secrets
        entry: detect-secrets scan
        language: system
        pass_filenames: false
        stages: [commit]
      - id: truffleHog
        name: truffleHog
        entry: truffleHog filesystem .
        language: system
        pass_filenames: false
        stages: [commit]

