repos:
  - repo: local
    hooks:
      - id: nix-fmt
        name: nix fmt
        entry: nix fmt
        language: system
        pass_filenames: false
        stages: [pre-commit]
      - id: detect-secrets
        name: detect-secrets
        entry: detect-secrets scan --baseline .secrets.baseline
        language: system
        pass_filenames: false
        stages: [pre-commit]
      - id: trufflehog
        name: trufflehog
        entry: trufflehog filesystem .
        language: system
        pass_filenames: false
        stages: [pre-commit]
